
//////////////////////////////////////////////////////////////////////////
============================= test session starts =============================
platform win32 -- Python 3.6.6, pytest-3.6.2, py-1.5.3, pluggy-0.6.0 -- c:\tools\python\py
thon.exe
cachedir: .pytest_cache
rootdir: C:\qp_lab\qpc\examples\qutest\unity_basic\test_qutest, inifile:
collected 5 items

test_ProductionCode.py::test_FindFunction_WhichIsBroken_ShouldReturnZeroIfItemIsNotInList_WhichWorksEvenInOurBrokenCode PASSED
test_ProductionCode.py::test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken FAILED
test_ProductionCode.py::test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken ERROR
test_ProductionCode.py::test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue ERROR
test_ProductionCode.py::test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValueAgain
Flushing text queue:
b'\x1c\x00B           Trg-Ack  QS_RX_TEST_SETUP'
PASSED
test_ProductionCode.py::test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed FAILED
test_ProductionCode.py::test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed ERROR

=================================== ERRORS ====================================
 ERROR at teardown of test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken
c:\tools\python\lib\site-packages\qspypy\fixtures.py:109: in qutest
    reset.call_on_teardown()
c:\tools\python\lib\site-packages\qspypy\qutest.py:258: in call_on_teardown
    self.expect('           Trg-Ack  QS_RX_TEST_TEARDOWN')
E   Failed: Expect Match Failed!
E   Expected:"           Trg-Ack  QS_RX_TEST_TEARDOWN"
E   Received:"0000000002 Trg-Done QS_RX_COMMAND"
 ERROR at setup of test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue
c:\tools\python\lib\site-packages\qspypy\fixtures.py:103: in qutest
    reset.call_on_setup()
c:\tools\python\lib\site-packages\qspypy\qutest.py:249: in call_on_setup
    self.expect('           Trg-Ack  QS_RX_TEST_SETUP')
E   Failed: Expect Match Failed!
E   Expected:"           Trg-Ack  QS_RX_TEST_SETUP"
E   Received:"           Trg-Ack  QS_RX_TEST_TEARDOWN"
 ERROR at teardown of test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed
c:\tools\python\lib\site-packages\qspypy\fixtures.py:109: in qutest
    reset.call_on_teardown()
c:\tools\python\lib\site-packages\qspypy\qutest.py:258: in call_on_teardown
    self.expect('           Trg-Ack  QS_RX_TEST_TEARDOWN')
E   Failed: Expect Match Failed!
E   Expected:"           Trg-Ack  QS_RX_TEST_TEARDOWN"
E   Received:"0000000002 Trg-Done QS_RX_COMMAND"
================================== FAILURES ===================================
 test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken
test_ProductionCode.py:38: in test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken
    qutest.expect("%timestamp USER+000 FindFunction_WhichIsBroken 1 34")
E   Failed: Expect Match Failed!
E   Expected:"0000000001 USER+000 FindFunction_WhichIsBroken 1 34"
E   Received:"0000000001 USER+000 FindFunction_WhichIsBroken 0 34"
 test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed
test_ProductionCode.py:69: in test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed
    qutest.expect("%timestamp USER+001 FunctionWhichReturnsLocalVariable 0x1234")
E   Failed: Expect Match Failed!
E   Expected:"0000000001 USER+001 FunctionWhichReturnsLocalVariable 0x1234"
E   Received:"0000000001 USER+001 FunctionWhichReturnsLocalVariable 0x5A5A"
================= 2 failed, 2 passed, 3 error in 5.25 seconds =================
make: *** [run] Error 1


//////////////////////////////////////////////////////////////////////////

tclsh C:\qp\qtools/qspy/tcl/qutest.tcl *.tcl build/test_basic.exe
QUTEST unit testing front-end 6.3.6
Copyright (c) 2005-2018 Quantum Leaps
help at: https://state-machine.com/qtools/qutest.html
Attaching to QSPY...OK (UDP-Port=59165)
----------------------------------------------
Group: test_ProductionCode.tcl
FindFunction_WhichIsBroken() Should Return Zero If Item Is Not In List, Which Works Even In Our Broken Code : passed (0.099s)
FindFunction_WhichIsBroken() Should Return The Index For Items In List, Which Will Fail Because Our Function Under Test Is Broken : ====> FAILED (0.972s) <====
Expected: "0000000001 USER+000 FindFunction_WhichIsBroken 1 34"
Received: "0000000001 USER+000 FindFunction_WhichIsBroken 0 34"
FunctionWhichReturnsLocalVariable() Should Return The Current Counter Value : passed (0.099s)
FunctionWhichReturnsLocalVariable() Should Return The Current Counter Value Again : passed (0.1s)
FunctionWhichReturnsLocalVariable() Should Return Current Counter, But Fails Because This Test Is Actually Flawed : ====> FAILED (0.517s) <====
Expected: "0000000001 USER+001 FunctionWhichReturnsLocalVariable 0x1234"
Received: "0000000001 USER+001 FunctionWhichReturnsLocalVariable 0x5A5A"
=========== Target: 181016_163545 ============
1 Groups 5 Tests 2 Failures 0 Skipped (5.691s)
FAIL!
make: *** [run] Error 1